{% set name = "pymc-bart" %}
{% set version = "0.8.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymc_bart-{{ version }}.tar.gz
  sha256: a7ebb43ed19604175e8d0db5112464ef040328801ceda9ba40892c3faf369d88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pymc >=5.16.2,<=5.19.1
    - arviz >=0.18.0
    - numba
    - matplotlib-base
    - numpy

test:
  imports:
    - pymc_bart
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/pymc-devs/pymc-bart
  summary: Bayesian Additive Regression Trees for Probabilistic programming with PyMC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ricardoV94
    - aloctavodia
    - maresb
