{% set name = "pymc-bart" %}
{% set version = "0.5.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymc_bart-{{ version }}.tar.gz
  sha256: 1229cd93789ff89d3d3b574f9d6723f30290b4d9db363aad51238f280aa0a41c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pymc >=5.0.0
    - arviz
    - numba
    - matplotlib-base
    - numpy <1.25.0

test:
  imports:
    - pymc_bart
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc-bart
  summary: Bayesian Additive Regression Trees for Probabilistic programming with PyMC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ricardoV94
    - aloctavodia
    - maresb
