{% set name = "pymc-bart" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymc_bart-{{ version }}.tar.gz
  sha256: ac16e39a35a421076383a281c5a86486b8323ea3a4a74fb523c3700867f50469

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pymc >=5.0.0
    - arviz
    - numba
    - matplotlib-base <=3.5.2

test:
  imports:
    - pymc_bart
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc-bart
  summary: Bayesian Additive Regression Trees for Probabilistic programming with PyMC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ricardoV94
    - aloctavodia
    - maresb
