{% set name = "pymc-bart" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymc_bart-{{ version }}.tar.gz
  sha256: 2279eaba14bcd6e8693b8727762ae1ec6eee02d3c6c046cc49c0a691355905eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pymc >=5.16.2,<=5.23.0
    - arviz >=0.18.0
    - numba
    - matplotlib-base
    - numpy

test:
  imports:
    - pymc_bart
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/pymc-devs/pymc-bart
  summary: Bayesian Additive Regression Trees for Probabilistic programming with PyMC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ricardoV94
    - aloctavodia
    - maresb
